// Mocks generated by Mockito 5.4.6 from annotations
// in awid_mobile/test/data/repositories/customer_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:awid_mobile/features/customer/data/datasources/customer_local_datasource.dart'
    as _i11;
import 'package:awid_mobile/features/customer/data/datasources/customer_remote_datasource.dart'
    as _i2;
import 'package:awid_mobile/features/customer/data/models/customer_account_model.dart'
    as _i7;
import 'package:awid_mobile/features/customer/data/models/customer_delivery_model.dart'
    as _i6;
import 'package:awid_mobile/features/customer/data/models/customer_notification_model.dart'
    as _i9;
import 'package:awid_mobile/features/customer/data/models/customer_order_model.dart'
    as _i4;
import 'package:awid_mobile/features/customer/domain/entities/customer_notification.dart'
    as _i10;
import 'package:awid_mobile/features/customer/domain/entities/customer_order.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CustomerRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRemoteDatasource extends _i1.Mock
    implements _i2.CustomerRemoteDatasource {
  MockCustomerRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CustomerOrderModel>> getOrders({
    required String? customerId,
    _i5.OrderStatus? status,
    DateTime? startDate,
    DateTime? endDate,
    String? searchQuery,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
          {
            #customerId: customerId,
            #status: status,
            #startDate: startDate,
            #endDate: endDate,
            #searchQuery: searchQuery,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i4.CustomerOrderModel>>.value(
            <_i4.CustomerOrderModel>[]),
      ) as _i3.Future<List<_i4.CustomerOrderModel>>);

  @override
  _i3.Future<_i4.CustomerOrderModel?> getOrder(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [orderId],
        ),
        returnValue: _i3.Future<_i4.CustomerOrderModel?>.value(),
      ) as _i3.Future<_i4.CustomerOrderModel?>);

  @override
  _i3.Future<List<_i4.CustomerOrderModel>> searchOrders(
    String? customerId,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchOrders,
          [
            customerId,
            query,
          ],
        ),
        returnValue: _i3.Future<List<_i4.CustomerOrderModel>>.value(
            <_i4.CustomerOrderModel>[]),
      ) as _i3.Future<List<_i4.CustomerOrderModel>>);

  @override
  _i3.Future<_i6.CustomerDeliveryModel?> getDelivery(String? deliveryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDelivery,
          [deliveryId],
        ),
        returnValue: _i3.Future<_i6.CustomerDeliveryModel?>.value(),
      ) as _i3.Future<_i6.CustomerDeliveryModel?>);

  @override
  _i3.Future<List<_i6.CustomerDeliveryModel>> getActiveDeliveries(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveDeliveries,
          [customerId],
        ),
        returnValue: _i3.Future<List<_i6.CustomerDeliveryModel>>.value(
            <_i6.CustomerDeliveryModel>[]),
      ) as _i3.Future<List<_i6.CustomerDeliveryModel>>);

  @override
  _i3.Future<List<_i6.CustomerDeliveryModel>> getDeliveriesHistory({
    required String? customerId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeliveriesHistory,
          [],
          {
            #customerId: customerId,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<_i6.CustomerDeliveryModel>>.value(
            <_i6.CustomerDeliveryModel>[]),
      ) as _i3.Future<List<_i6.CustomerDeliveryModel>>);

  @override
  _i3.Future<_i7.CustomerAccountModel?> getAccountInfo(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountInfo,
          [customerId],
        ),
        returnValue: _i3.Future<_i7.CustomerAccountModel?>.value(),
      ) as _i3.Future<_i7.CustomerAccountModel?>);

  @override
  _i3.Future<_i7.CustomerCreditInfoModel?> getCreditInfo(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCreditInfo,
          [customerId],
        ),
        returnValue: _i3.Future<_i7.CustomerCreditInfoModel?>.value(),
      ) as _i3.Future<_i7.CustomerCreditInfoModel?>);

  @override
  _i3.Future<_i7.CustomerPackagingInfoModel?> getPackagingInfo(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingInfo,
          [customerId],
        ),
        returnValue: _i3.Future<_i7.CustomerPackagingInfoModel?>.value(),
      ) as _i3.Future<_i7.CustomerPackagingInfoModel?>);

  @override
  _i3.Future<void> updateSettings(
    String? customerId,
    _i7.CustomerSettingsModel? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSettings,
          [
            customerId,
            settings,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateContact(
    String? customerId,
    String? contactId,
    _i7.CustomerContactModel? contact,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContact,
          [
            customerId,
            contactId,
            contact,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> addContact(
    String? customerId,
    _i7.CustomerContactModel? contact,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addContact,
          [
            customerId,
            contact,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #addContact,
            [
              customerId,
              contact,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> deleteContact(
    String? customerId,
    String? contactId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteContact,
          [
            customerId,
            contactId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.CustomerNotificationModel>> getNotifications({
    required String? customerId,
    _i10.NotificationType? type,
    bool? isRead,
    _i10.NotificationPriority? priority,
    DateTime? startDate,
    DateTime? endDate,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
          {
            #customerId: customerId,
            #type: type,
            #isRead: isRead,
            #priority: priority,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i9.CustomerNotificationModel>>.value(
            <_i9.CustomerNotificationModel>[]),
      ) as _i3.Future<List<_i9.CustomerNotificationModel>>);

  @override
  _i3.Future<int> getUnreadNotificationsCount(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadNotificationsCount,
          [customerId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> markNotificationAsRead(
    String? customerId,
    String? notificationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markNotificationAsRead,
          [
            customerId,
            notificationId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> markAllNotificationsAsRead(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAllNotificationsAsRead,
          [customerId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> deleteNotification(
    String? customerId,
    String? notificationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotification,
          [
            customerId,
            notificationId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> deleteReadNotifications(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteReadNotifications,
          [customerId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [CustomerLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerLocalDatasource extends _i1.Mock
    implements _i11.CustomerLocalDatasource {
  MockCustomerLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheOrders(
    String? customerId,
    List<_i4.CustomerOrderModel>? orders,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheOrders,
          [
            customerId,
            orders,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.CustomerOrderModel>?> getCachedOrders(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedOrders,
          [customerId],
        ),
        returnValue: _i3.Future<List<_i4.CustomerOrderModel>?>.value(),
      ) as _i3.Future<List<_i4.CustomerOrderModel>?>);

  @override
  _i3.Future<void> cacheOrder(_i4.CustomerOrderModel? order) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheOrder,
          [order],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.CustomerOrderModel?> getCachedOrder(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedOrder,
          [orderId],
        ),
        returnValue: _i3.Future<_i4.CustomerOrderModel?>.value(),
      ) as _i3.Future<_i4.CustomerOrderModel?>);

  @override
  _i3.Future<void> clearOrdersCache(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #clearOrdersCache,
          [customerId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheDeliveries(
    String? customerId,
    List<_i6.CustomerDeliveryModel>? deliveries,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheDeliveries,
          [
            customerId,
            deliveries,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.CustomerDeliveryModel>?> getCachedDeliveries(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedDeliveries,
          [customerId],
        ),
        returnValue: _i3.Future<List<_i6.CustomerDeliveryModel>?>.value(),
      ) as _i3.Future<List<_i6.CustomerDeliveryModel>?>);

  @override
  _i3.Future<void> cacheDelivery(_i6.CustomerDeliveryModel? delivery) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheDelivery,
          [delivery],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.CustomerDeliveryModel?> getCachedDelivery(
          String? deliveryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedDelivery,
          [deliveryId],
        ),
        returnValue: _i3.Future<_i6.CustomerDeliveryModel?>.value(),
      ) as _i3.Future<_i6.CustomerDeliveryModel?>);

  @override
  _i3.Future<void> clearDeliveriesCache(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearDeliveriesCache,
          [customerId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheAccountInfo(_i7.CustomerAccountModel? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAccountInfo,
          [account],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i7.CustomerAccountModel?> getCachedAccountInfo(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedAccountInfo,
          [customerId],
        ),
        returnValue: _i3.Future<_i7.CustomerAccountModel?>.value(),
      ) as _i3.Future<_i7.CustomerAccountModel?>);

  @override
  _i3.Future<void> clearAccountCache(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #clearAccountCache,
          [customerId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheNotifications(
    String? customerId,
    List<_i9.CustomerNotificationModel>? notifications,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheNotifications,
          [
            customerId,
            notifications,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.CustomerNotificationModel>?> getCachedNotifications(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNotifications,
          [customerId],
        ),
        returnValue: _i3.Future<List<_i9.CustomerNotificationModel>?>.value(),
      ) as _i3.Future<List<_i9.CustomerNotificationModel>?>);

  @override
  _i3.Future<void> markNotificationAsReadInCache(
    String? customerId,
    String? notificationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markNotificationAsReadInCache,
          [
            customerId,
            notificationId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNotificationFromCache(
    String? customerId,
    String? notificationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotificationFromCache,
          [
            customerId,
            notificationId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearNotificationsCache(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearNotificationsCache,
          [customerId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllCache(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [customerId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> hasCachedData(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #hasCachedData,
          [customerId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
