// Mocks generated by Mockito 5.4.6 from annotations
// in awid_mobile/test/data/repositories/delivery_actions_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:awid_mobile/core/storage/local_storage.dart' as _i8;
import 'package:awid_mobile/features/deliverer/data/datasources/delivery_actions_remote_datasource.dart'
    as _i6;
import 'package:awid_mobile/features/deliverer/data/models/packaging_transaction_model.dart'
    as _i4;
import 'package:awid_mobile/features/deliverer/data/models/payment_collection_model.dart'
    as _i3;
import 'package:awid_mobile/features/deliverer/data/models/proof_of_delivery_model.dart'
    as _i2;
import 'package:hive_flutter/hive_flutter.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUploadProofResponse_0 extends _i1.SmartFake
    implements _i2.UploadProofResponse {
  _FakeUploadProofResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUploadPaymentResponse_1 extends _i1.SmartFake
    implements _i3.UploadPaymentResponse {
  _FakeUploadPaymentResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUploadPackagingTransactionResponse_2 extends _i1.SmartFake
    implements _i4.UploadPackagingTransactionResponse {
  _FakeUploadPackagingTransactionResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePackagingBalanceModel_3 extends _i1.SmartFake
    implements _i4.PackagingBalanceModel {
  _FakePackagingBalanceModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_4<E> extends _i1.SmartFake implements _i5.Box<E> {
  _FakeBox_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DeliveryActionsRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeliveryActionsRemoteDatasource extends _i1.Mock
    implements _i6.DeliveryActionsRemoteDatasource {
  MockDeliveryActionsRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.UploadProofResponse> uploadProofOfDelivery({
    required String? deliveryId,
    required String? delivererId,
    required String? customerId,
    required DateTime? timestamp,
    required double? latitude,
    required double? longitude,
    required String? signatoryName,
    required String? signatureImagePath,
    required List<String>? photosPaths,
    String? notes,
    String? customerFeedback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProofOfDelivery,
          [],
          {
            #deliveryId: deliveryId,
            #delivererId: delivererId,
            #customerId: customerId,
            #timestamp: timestamp,
            #latitude: latitude,
            #longitude: longitude,
            #signatoryName: signatoryName,
            #signatureImagePath: signatureImagePath,
            #photosPaths: photosPaths,
            #notes: notes,
            #customerFeedback: customerFeedback,
          },
        ),
        returnValue: _i7.Future<_i2.UploadProofResponse>.value(
            _FakeUploadProofResponse_0(
          this,
          Invocation.method(
            #uploadProofOfDelivery,
            [],
            {
              #deliveryId: deliveryId,
              #delivererId: delivererId,
              #customerId: customerId,
              #timestamp: timestamp,
              #latitude: latitude,
              #longitude: longitude,
              #signatoryName: signatoryName,
              #signatureImagePath: signatureImagePath,
              #photosPaths: photosPaths,
              #notes: notes,
              #customerFeedback: customerFeedback,
            },
          ),
        )),
      ) as _i7.Future<_i2.UploadProofResponse>);

  @override
  _i7.Future<List<_i2.ProofOfDeliveryModel>> getProofsOfDelivery({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    bool? isUploaded,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProofsOfDelivery,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #isUploaded: isUploaded,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i7.Future<List<_i2.ProofOfDeliveryModel>>.value(
            <_i2.ProofOfDeliveryModel>[]),
      ) as _i7.Future<List<_i2.ProofOfDeliveryModel>>);

  @override
  _i7.Future<_i2.ProofOfDeliveryModel?> getProofOfDelivery(String? proofId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProofOfDelivery,
          [proofId],
        ),
        returnValue: _i7.Future<_i2.ProofOfDeliveryModel?>.value(),
      ) as _i7.Future<_i2.ProofOfDeliveryModel?>);

  @override
  _i7.Future<_i3.UploadPaymentResponse> uploadPaymentCollection({
    required String? delivererId,
    required String? customerId,
    required String? customerName,
    required double? amount,
    required String? mode,
    required DateTime? collectedAt,
    required List<Map<String, dynamic>>? allocations,
    String? reference,
    String? notes,
    String? receiptImagePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPaymentCollection,
          [],
          {
            #delivererId: delivererId,
            #customerId: customerId,
            #customerName: customerName,
            #amount: amount,
            #mode: mode,
            #collectedAt: collectedAt,
            #allocations: allocations,
            #reference: reference,
            #notes: notes,
            #receiptImagePath: receiptImagePath,
          },
        ),
        returnValue: _i7.Future<_i3.UploadPaymentResponse>.value(
            _FakeUploadPaymentResponse_1(
          this,
          Invocation.method(
            #uploadPaymentCollection,
            [],
            {
              #delivererId: delivererId,
              #customerId: customerId,
              #customerName: customerName,
              #amount: amount,
              #mode: mode,
              #collectedAt: collectedAt,
              #allocations: allocations,
              #reference: reference,
              #notes: notes,
              #receiptImagePath: receiptImagePath,
            },
          ),
        )),
      ) as _i7.Future<_i3.UploadPaymentResponse>);

  @override
  _i7.Future<List<_i3.PaymentCollectionModel>> getPaymentCollections({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    String? mode,
    bool? isUploaded,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentCollections,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #mode: mode,
            #isUploaded: isUploaded,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i7.Future<List<_i3.PaymentCollectionModel>>.value(
            <_i3.PaymentCollectionModel>[]),
      ) as _i7.Future<List<_i3.PaymentCollectionModel>>);

  @override
  _i7.Future<List<_i3.UnpaidOrderModel>> getUnpaidOrders(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnpaidOrders,
          [customerId],
        ),
        returnValue: _i7.Future<List<_i3.UnpaidOrderModel>>.value(
            <_i3.UnpaidOrderModel>[]),
      ) as _i7.Future<List<_i3.UnpaidOrderModel>>);

  @override
  _i7.Future<List<_i3.PaymentAllocationModel>> calculateAutoAllocation({
    required String? customerId,
    required double? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateAutoAllocation,
          [],
          {
            #customerId: customerId,
            #amount: amount,
          },
        ),
        returnValue: _i7.Future<List<_i3.PaymentAllocationModel>>.value(
            <_i3.PaymentAllocationModel>[]),
      ) as _i7.Future<List<_i3.PaymentAllocationModel>>);

  @override
  _i7.Future<_i4.UploadPackagingTransactionResponse>
      uploadPackagingTransaction({
    required String? delivererId,
    required String? customerId,
    required String? customerName,
    required String? type,
    required List<Map<String, dynamic>>? items,
    required DateTime? transactionDate,
    String? notes,
    String? qrCodeData,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #uploadPackagingTransaction,
              [],
              {
                #delivererId: delivererId,
                #customerId: customerId,
                #customerName: customerName,
                #type: type,
                #items: items,
                #transactionDate: transactionDate,
                #notes: notes,
                #qrCodeData: qrCodeData,
              },
            ),
            returnValue:
                _i7.Future<_i4.UploadPackagingTransactionResponse>.value(
                    _FakeUploadPackagingTransactionResponse_2(
              this,
              Invocation.method(
                #uploadPackagingTransaction,
                [],
                {
                  #delivererId: delivererId,
                  #customerId: customerId,
                  #customerName: customerName,
                  #type: type,
                  #items: items,
                  #transactionDate: transactionDate,
                  #notes: notes,
                  #qrCodeData: qrCodeData,
                },
              ),
            )),
          ) as _i7.Future<_i4.UploadPackagingTransactionResponse>);

  @override
  _i7.Future<List<_i4.PackagingTransactionModel>> getPackagingTransactions({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    String? type,
    bool? isUploaded,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingTransactions,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #type: type,
            #isUploaded: isUploaded,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i7.Future<List<_i4.PackagingTransactionModel>>.value(
            <_i4.PackagingTransactionModel>[]),
      ) as _i7.Future<List<_i4.PackagingTransactionModel>>);

  @override
  _i7.Future<_i4.PackagingBalanceModel> getPackagingBalance(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingBalance,
          [customerId],
        ),
        returnValue: _i7.Future<_i4.PackagingBalanceModel>.value(
            _FakePackagingBalanceModel_3(
          this,
          Invocation.method(
            #getPackagingBalance,
            [customerId],
          ),
        )),
      ) as _i7.Future<_i4.PackagingBalanceModel>);

  @override
  _i7.Future<List<_i4.PackagingTypeModel>> getPackagingTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingTypes,
          [],
        ),
        returnValue: _i7.Future<List<_i4.PackagingTypeModel>>.value(
            <_i4.PackagingTypeModel>[]),
      ) as _i7.Future<List<_i4.PackagingTypeModel>>);

  @override
  _i7.Future<_i4.PackagingQrDataModel?> scanPackagingQrCode(String? qrData) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanPackagingQrCode,
          [qrData],
        ),
        returnValue: _i7.Future<_i4.PackagingQrDataModel?>.value(),
      ) as _i7.Future<_i4.PackagingQrDataModel?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getDeliveryHistory({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    String? status,
    String? customerId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeliveryHistory,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #status: status,
            #customerId: customerId,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<Map<String, dynamic>> getDelivererEarnings({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDelivererEarnings,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getDetailedStats({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailedStats,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> syncAllPendingData(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncAllPendingData,
          [delivererId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getSyncStatus(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncStatus,
          [delivererId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);
}

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i8.LocalStorage {
  MockLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Box<T>> openBox<T>(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [boxName],
        ),
        returnValue: _i7.Future<_i5.Box<T>>.value(_FakeBox_4<T>(
          this,
          Invocation.method(
            #openBox,
            [boxName],
          ),
        )),
      ) as _i7.Future<_i5.Box<T>>);

  @override
  _i7.Future<void> closeBox(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #closeBox,
          [boxName],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> write<T>(
    String? boxName,
    String? key,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            boxName,
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<T?> read<T>(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i7.Future<T?>.value(),
      ) as _i7.Future<T?>);

  @override
  _i7.Future<void> delete(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clear(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [boxName],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<String>> getKeys(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [boxName],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<List<T>> getValues<T>(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #getValues,
          [boxName],
        ),
        returnValue: _i7.Future<List<T>>.value(<T>[]),
      ) as _i7.Future<List<T>>);

  @override
  _i7.Future<bool> containsKey(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<int> length(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #length,
          [boxName],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> writeAll<T>(
    String? boxName,
    Map<String, T>? entries,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAll,
          [
            boxName,
            entries,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteAll(
    String? boxName,
    List<String>? keys,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [
            boxName,
            keys,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
