// Mocks generated by Mockito 5.4.6 from annotations
// in awid_mobile/test/data/repositories/kitchen_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:awid_mobile/features/kitchen/data/datasources/kitchen_local_datasource.dart'
    as _i13;
import 'package:awid_mobile/features/kitchen/data/datasources/kitchen_remote_datasource.dart'
    as _i7;
import 'package:awid_mobile/features/kitchen/data/models/kitchen_order_model.dart'
    as _i2;
import 'package:awid_mobile/features/kitchen/data/models/kitchen_station_model.dart'
    as _i3;
import 'package:awid_mobile/features/kitchen/data/models/kitchen_stats_model.dart'
    as _i5;
import 'package:awid_mobile/features/kitchen/data/models/production_task_model.dart'
    as _i6;
import 'package:awid_mobile/features/kitchen/data/models/stock_item_model.dart'
    as _i4;
import 'package:awid_mobile/features/kitchen/domain/entities/kitchen_order.dart'
    as _i9;
import 'package:awid_mobile/features/kitchen/domain/entities/kitchen_station.dart'
    as _i10;
import 'package:awid_mobile/features/kitchen/domain/entities/production_task.dart'
    as _i12;
import 'package:awid_mobile/features/kitchen/domain/entities/stock_item.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKitchenOrderModel_0 extends _i1.SmartFake
    implements _i2.KitchenOrderModel {
  _FakeKitchenOrderModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKitchenStationModel_1 extends _i1.SmartFake
    implements _i3.KitchenStationModel {
  _FakeKitchenStationModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStockItemModel_2 extends _i1.SmartFake
    implements _i4.StockItemModel {
  _FakeStockItemModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKitchenStatsModel_3 extends _i1.SmartFake
    implements _i5.KitchenStatsModel {
  _FakeKitchenStatsModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeriodStatsModel_4 extends _i1.SmartFake
    implements _i5.PeriodStatsModel {
  _FakePeriodStatsModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductionTaskModel_5 extends _i1.SmartFake
    implements _i6.ProductionTaskModel {
  _FakeProductionTaskModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KitchenRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockKitchenRemoteDatasource extends _i1.Mock
    implements _i7.KitchenRemoteDatasource {
  MockKitchenRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i2.KitchenOrderModel>> getOrders({
    _i9.KitchenOrderStatus? status,
    _i9.OrderPriority? priority,
    String? stationId,
    DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
          {
            #status: status,
            #priority: priority,
            #stationId: stationId,
            #date: date,
          },
        ),
        returnValue: _i8.Future<List<_i2.KitchenOrderModel>>.value(
            <_i2.KitchenOrderModel>[]),
      ) as _i8.Future<List<_i2.KitchenOrderModel>>);

  @override
  _i8.Future<_i2.KitchenOrderModel> getOrderById(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderById,
          [orderId],
        ),
        returnValue:
            _i8.Future<_i2.KitchenOrderModel>.value(_FakeKitchenOrderModel_0(
          this,
          Invocation.method(
            #getOrderById,
            [orderId],
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrderModel>);

  @override
  _i8.Future<_i2.KitchenOrderModel> updateOrderStatus({
    required String? orderId,
    required _i9.KitchenOrderStatus? status,
    String? stationId,
    String? staffId,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatus,
          [],
          {
            #orderId: orderId,
            #status: status,
            #stationId: stationId,
            #staffId: staffId,
            #notes: notes,
          },
        ),
        returnValue:
            _i8.Future<_i2.KitchenOrderModel>.value(_FakeKitchenOrderModel_0(
          this,
          Invocation.method(
            #updateOrderStatus,
            [],
            {
              #orderId: orderId,
              #status: status,
              #stationId: stationId,
              #staffId: staffId,
              #notes: notes,
            },
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrderModel>);

  @override
  _i8.Future<_i2.KitchenOrderModel> assignOrderToStation({
    required String? orderId,
    required String? stationId,
    String? staffId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignOrderToStation,
          [],
          {
            #orderId: orderId,
            #stationId: stationId,
            #staffId: staffId,
          },
        ),
        returnValue:
            _i8.Future<_i2.KitchenOrderModel>.value(_FakeKitchenOrderModel_0(
          this,
          Invocation.method(
            #assignOrderToStation,
            [],
            {
              #orderId: orderId,
              #stationId: stationId,
              #staffId: staffId,
            },
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrderModel>);

  @override
  _i8.Future<_i2.KitchenOrderModel> updateOrderPriority({
    required String? orderId,
    required _i9.OrderPriority? priority,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderPriority,
          [],
          {
            #orderId: orderId,
            #priority: priority,
          },
        ),
        returnValue:
            _i8.Future<_i2.KitchenOrderModel>.value(_FakeKitchenOrderModel_0(
          this,
          Invocation.method(
            #updateOrderPriority,
            [],
            {
              #orderId: orderId,
              #priority: priority,
            },
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrderModel>);

  @override
  _i8.Future<_i2.KitchenOrderModel> updateOrderNotes({
    required String? orderId,
    required String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderNotes,
          [],
          {
            #orderId: orderId,
            #notes: notes,
          },
        ),
        returnValue:
            _i8.Future<_i2.KitchenOrderModel>.value(_FakeKitchenOrderModel_0(
          this,
          Invocation.method(
            #updateOrderNotes,
            [],
            {
              #orderId: orderId,
              #notes: notes,
            },
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrderModel>);

  @override
  _i8.Future<_i2.KitchenOrderModel> markItemPrepared({
    required String? orderId,
    required String? itemId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markItemPrepared,
          [],
          {
            #orderId: orderId,
            #itemId: itemId,
          },
        ),
        returnValue:
            _i8.Future<_i2.KitchenOrderModel>.value(_FakeKitchenOrderModel_0(
          this,
          Invocation.method(
            #markItemPrepared,
            [],
            {
              #orderId: orderId,
              #itemId: itemId,
            },
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrderModel>);

  @override
  _i8.Future<List<_i3.KitchenStationModel>> getStations({
    _i10.StationType? type,
    _i10.StationStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStations,
          [],
          {
            #type: type,
            #status: status,
          },
        ),
        returnValue: _i8.Future<List<_i3.KitchenStationModel>>.value(
            <_i3.KitchenStationModel>[]),
      ) as _i8.Future<List<_i3.KitchenStationModel>>);

  @override
  _i8.Future<_i3.KitchenStationModel> getStationById(String? stationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStationById,
          [stationId],
        ),
        returnValue: _i8.Future<_i3.KitchenStationModel>.value(
            _FakeKitchenStationModel_1(
          this,
          Invocation.method(
            #getStationById,
            [stationId],
          ),
        )),
      ) as _i8.Future<_i3.KitchenStationModel>);

  @override
  _i8.Future<_i3.KitchenStationModel> updateStationStatus({
    required String? stationId,
    required _i10.StationStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStationStatus,
          [],
          {
            #stationId: stationId,
            #status: status,
          },
        ),
        returnValue: _i8.Future<_i3.KitchenStationModel>.value(
            _FakeKitchenStationModel_1(
          this,
          Invocation.method(
            #updateStationStatus,
            [],
            {
              #stationId: stationId,
              #status: status,
            },
          ),
        )),
      ) as _i8.Future<_i3.KitchenStationModel>);

  @override
  _i8.Future<_i3.KitchenStationModel> assignStaffToStation({
    required String? stationId,
    required String? staffId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignStaffToStation,
          [],
          {
            #stationId: stationId,
            #staffId: staffId,
          },
        ),
        returnValue: _i8.Future<_i3.KitchenStationModel>.value(
            _FakeKitchenStationModel_1(
          this,
          Invocation.method(
            #assignStaffToStation,
            [],
            {
              #stationId: stationId,
              #staffId: staffId,
            },
          ),
        )),
      ) as _i8.Future<_i3.KitchenStationModel>);

  @override
  _i8.Future<List<_i4.StockItemModel>> getStockItems({
    String? category,
    _i11.StockLevel? level,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockItems,
          [],
          {
            #category: category,
            #level: level,
          },
        ),
        returnValue:
            _i8.Future<List<_i4.StockItemModel>>.value(<_i4.StockItemModel>[]),
      ) as _i8.Future<List<_i4.StockItemModel>>);

  @override
  _i8.Future<_i4.StockItemModel> getStockItemById(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockItemById,
          [itemId],
        ),
        returnValue: _i8.Future<_i4.StockItemModel>.value(_FakeStockItemModel_2(
          this,
          Invocation.method(
            #getStockItemById,
            [itemId],
          ),
        )),
      ) as _i8.Future<_i4.StockItemModel>);

  @override
  _i8.Future<_i4.StockItemModel> adjustStockQuantity({
    required String? itemId,
    required double? quantity,
    required _i11.StockMovementType? type,
    String? reason,
    String? orderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adjustStockQuantity,
          [],
          {
            #itemId: itemId,
            #quantity: quantity,
            #type: type,
            #reason: reason,
            #orderId: orderId,
          },
        ),
        returnValue: _i8.Future<_i4.StockItemModel>.value(_FakeStockItemModel_2(
          this,
          Invocation.method(
            #adjustStockQuantity,
            [],
            {
              #itemId: itemId,
              #quantity: quantity,
              #type: type,
              #reason: reason,
              #orderId: orderId,
            },
          ),
        )),
      ) as _i8.Future<_i4.StockItemModel>);

  @override
  _i8.Future<_i4.StockItemModel> createStockItem(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStockItem,
          [data],
        ),
        returnValue: _i8.Future<_i4.StockItemModel>.value(_FakeStockItemModel_2(
          this,
          Invocation.method(
            #createStockItem,
            [data],
          ),
        )),
      ) as _i8.Future<_i4.StockItemModel>);

  @override
  _i8.Future<_i4.StockItemModel> updateStockItem({
    required String? itemId,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStockItem,
          [],
          {
            #itemId: itemId,
            #data: data,
          },
        ),
        returnValue: _i8.Future<_i4.StockItemModel>.value(_FakeStockItemModel_2(
          this,
          Invocation.method(
            #updateStockItem,
            [],
            {
              #itemId: itemId,
              #data: data,
            },
          ),
        )),
      ) as _i8.Future<_i4.StockItemModel>);

  @override
  _i8.Future<List<_i4.StockMovementModel>> getStockMovements({
    String? itemId,
    DateTime? startDate,
    DateTime? endDate,
    _i11.StockMovementType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockMovements,
          [],
          {
            #itemId: itemId,
            #startDate: startDate,
            #endDate: endDate,
            #type: type,
          },
        ),
        returnValue: _i8.Future<List<_i4.StockMovementModel>>.value(
            <_i4.StockMovementModel>[]),
      ) as _i8.Future<List<_i4.StockMovementModel>>);

  @override
  _i8.Future<List<_i4.StockAlertModel>> getStockAlerts(
          {bool? activeOnly = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockAlerts,
          [],
          {#activeOnly: activeOnly},
        ),
        returnValue: _i8.Future<List<_i4.StockAlertModel>>.value(
            <_i4.StockAlertModel>[]),
      ) as _i8.Future<List<_i4.StockAlertModel>>);

  @override
  _i8.Future<void> resolveStockAlert(String? alertId) => (super.noSuchMethod(
        Invocation.method(
          #resolveStockAlert,
          [alertId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.KitchenStatsModel> getStats({DateTime? date}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
          {#date: date},
        ),
        returnValue:
            _i8.Future<_i5.KitchenStatsModel>.value(_FakeKitchenStatsModel_3(
          this,
          Invocation.method(
            #getStats,
            [],
            {#date: date},
          ),
        )),
      ) as _i8.Future<_i5.KitchenStatsModel>);

  @override
  _i8.Future<_i5.PeriodStatsModel> getPeriodStats({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPeriodStats,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i8.Future<_i5.PeriodStatsModel>.value(_FakePeriodStatsModel_4(
          this,
          Invocation.method(
            #getPeriodStats,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i8.Future<_i5.PeriodStatsModel>);

  @override
  _i8.Future<List<_i5.HourlyStatsModel>> getHourlyStats({DateTime? date}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHourlyStats,
          [],
          {#date: date},
        ),
        returnValue: _i8.Future<List<_i5.HourlyStatsModel>>.value(
            <_i5.HourlyStatsModel>[]),
      ) as _i8.Future<List<_i5.HourlyStatsModel>>);

  @override
  _i8.Future<List<_i6.ProductionTaskModel>> getProductionTasks({
    _i12.TaskStatus? status,
    _i12.TaskType? type,
    String? stationId,
    DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductionTasks,
          [],
          {
            #status: status,
            #type: type,
            #stationId: stationId,
            #date: date,
          },
        ),
        returnValue: _i8.Future<List<_i6.ProductionTaskModel>>.value(
            <_i6.ProductionTaskModel>[]),
      ) as _i8.Future<List<_i6.ProductionTaskModel>>);

  @override
  _i8.Future<_i6.ProductionTaskModel> getTaskById(String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [taskId],
        ),
        returnValue: _i8.Future<_i6.ProductionTaskModel>.value(
            _FakeProductionTaskModel_5(
          this,
          Invocation.method(
            #getTaskById,
            [taskId],
          ),
        )),
      ) as _i8.Future<_i6.ProductionTaskModel>);

  @override
  _i8.Future<_i6.ProductionTaskModel> updateTaskStatus({
    required String? taskId,
    required _i12.TaskStatus? status,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTaskStatus,
          [],
          {
            #taskId: taskId,
            #status: status,
            #notes: notes,
          },
        ),
        returnValue: _i8.Future<_i6.ProductionTaskModel>.value(
            _FakeProductionTaskModel_5(
          this,
          Invocation.method(
            #updateTaskStatus,
            [],
            {
              #taskId: taskId,
              #status: status,
              #notes: notes,
            },
          ),
        )),
      ) as _i8.Future<_i6.ProductionTaskModel>);

  @override
  _i8.Future<_i6.ProductionTaskModel> assignTask({
    required String? taskId,
    required String? stationId,
    String? staffId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignTask,
          [],
          {
            #taskId: taskId,
            #stationId: stationId,
            #staffId: staffId,
          },
        ),
        returnValue: _i8.Future<_i6.ProductionTaskModel>.value(
            _FakeProductionTaskModel_5(
          this,
          Invocation.method(
            #assignTask,
            [],
            {
              #taskId: taskId,
              #stationId: stationId,
              #staffId: staffId,
            },
          ),
        )),
      ) as _i8.Future<_i6.ProductionTaskModel>);

  @override
  _i8.Future<_i6.ProductionTaskModel> completeTaskStep({
    required String? taskId,
    required String? stepId,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTaskStep,
          [],
          {
            #taskId: taskId,
            #stepId: stepId,
            #notes: notes,
          },
        ),
        returnValue: _i8.Future<_i6.ProductionTaskModel>.value(
            _FakeProductionTaskModel_5(
          this,
          Invocation.method(
            #completeTaskStep,
            [],
            {
              #taskId: taskId,
              #stepId: stepId,
              #notes: notes,
            },
          ),
        )),
      ) as _i8.Future<_i6.ProductionTaskModel>);
}

/// A class which mocks [KitchenLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockKitchenLocalDatasource extends _i1.Mock
    implements _i13.KitchenLocalDatasource {
  MockKitchenLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> cacheOrders(List<_i2.KitchenOrderModel>? orders) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheOrders,
          [orders],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.KitchenOrderModel>?> getCachedOrders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedOrders,
          [],
        ),
        returnValue: _i8.Future<List<_i2.KitchenOrderModel>?>.value(),
      ) as _i8.Future<List<_i2.KitchenOrderModel>?>);

  @override
  _i8.Future<void> cacheOrder(_i2.KitchenOrderModel? order) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheOrder,
          [order],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i2.KitchenOrderModel?> getCachedOrder(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedOrder,
          [orderId],
        ),
        returnValue: _i8.Future<_i2.KitchenOrderModel?>.value(),
      ) as _i8.Future<_i2.KitchenOrderModel?>);

  @override
  _i8.Future<void> deleteOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #deleteOrder,
          [orderId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cacheStations(List<_i3.KitchenStationModel>? stations) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheStations,
          [stations],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.KitchenStationModel>?> getCachedStations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedStations,
          [],
        ),
        returnValue: _i8.Future<List<_i3.KitchenStationModel>?>.value(),
      ) as _i8.Future<List<_i3.KitchenStationModel>?>);

  @override
  _i8.Future<void> cacheStockItems(List<_i4.StockItemModel>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheStockItems,
          [items],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.StockItemModel>?> getCachedStockItems() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedStockItems,
          [],
        ),
        returnValue: _i8.Future<List<_i4.StockItemModel>?>.value(),
      ) as _i8.Future<List<_i4.StockItemModel>?>);

  @override
  _i8.Future<void> cacheStockItem(_i4.StockItemModel? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheStockItem,
          [item],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.StockItemModel?> getCachedStockItem(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedStockItem,
          [itemId],
        ),
        returnValue: _i8.Future<_i4.StockItemModel?>.value(),
      ) as _i8.Future<_i4.StockItemModel?>);

  @override
  _i8.Future<void> cacheStats(_i5.KitchenStatsModel? stats) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheStats,
          [stats],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.KitchenStatsModel?> getCachedStats(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedStats,
          [date],
        ),
        returnValue: _i8.Future<_i5.KitchenStatsModel?>.value(),
      ) as _i8.Future<_i5.KitchenStatsModel?>);

  @override
  _i8.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearOrdersCache() => (super.noSuchMethod(
        Invocation.method(
          #clearOrdersCache,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearStockCache() => (super.noSuchMethod(
        Invocation.method(
          #clearStockCache,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
