// Mocks generated by Mockito 5.4.6 from annotations
// in awid_mobile/test/domain/usecases/get_orders_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:awid_mobile/features/customer/domain/entities/customer_account.dart'
    as _i6;
import 'package:awid_mobile/features/customer/domain/entities/customer_delivery.dart'
    as _i5;
import 'package:awid_mobile/features/customer/domain/entities/customer_notification.dart'
    as _i8;
import 'package:awid_mobile/features/customer/domain/entities/customer_order.dart'
    as _i4;
import 'package:awid_mobile/features/customer/domain/repositories/customer_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CustomerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRepository extends _i1.Mock
    implements _i2.CustomerRepository {
  MockCustomerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CustomerOrder>> getOrders({
    required String? customerId,
    _i4.OrderStatus? status,
    DateTime? startDate,
    DateTime? endDate,
    String? searchQuery,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
          {
            #customerId: customerId,
            #status: status,
            #startDate: startDate,
            #endDate: endDate,
            #searchQuery: searchQuery,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i3.Future<List<_i4.CustomerOrder>>.value(<_i4.CustomerOrder>[]),
      ) as _i3.Future<List<_i4.CustomerOrder>>);

  @override
  _i3.Future<_i4.CustomerOrder?> getOrder(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [orderId],
        ),
        returnValue: _i3.Future<_i4.CustomerOrder?>.value(),
      ) as _i3.Future<_i4.CustomerOrder?>);

  @override
  _i3.Future<List<_i4.CustomerOrder>> getActiveOrders(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveOrders,
          [customerId],
        ),
        returnValue:
            _i3.Future<List<_i4.CustomerOrder>>.value(<_i4.CustomerOrder>[]),
      ) as _i3.Future<List<_i4.CustomerOrder>>);

  @override
  _i3.Future<List<_i4.CustomerOrder>> searchOrders(
    String? customerId,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchOrders,
          [
            customerId,
            query,
          ],
        ),
        returnValue:
            _i3.Future<List<_i4.CustomerOrder>>.value(<_i4.CustomerOrder>[]),
      ) as _i3.Future<List<_i4.CustomerOrder>>);

  @override
  _i3.Future<_i5.CustomerDelivery?> getDelivery(String? deliveryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDelivery,
          [deliveryId],
        ),
        returnValue: _i3.Future<_i5.CustomerDelivery?>.value(),
      ) as _i3.Future<_i5.CustomerDelivery?>);

  @override
  _i3.Future<List<_i5.CustomerDelivery>> getActiveDeliveries(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveDeliveries,
          [customerId],
        ),
        returnValue: _i3.Future<List<_i5.CustomerDelivery>>.value(
            <_i5.CustomerDelivery>[]),
      ) as _i3.Future<List<_i5.CustomerDelivery>>);

  @override
  _i3.Future<List<_i5.CustomerDelivery>> getDeliveriesHistory({
    required String? customerId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeliveriesHistory,
          [],
          {
            #customerId: customerId,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<_i5.CustomerDelivery>>.value(
            <_i5.CustomerDelivery>[]),
      ) as _i3.Future<List<_i5.CustomerDelivery>>);

  @override
  _i3.Stream<_i5.CustomerDelivery> subscribeToDeliveryUpdates(
          String? deliveryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToDeliveryUpdates,
          [deliveryId],
        ),
        returnValue: _i3.Stream<_i5.CustomerDelivery>.empty(),
      ) as _i3.Stream<_i5.CustomerDelivery>);

  @override
  _i3.Future<_i6.CustomerAccount?> getAccountInfo(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountInfo,
          [customerId],
        ),
        returnValue: _i3.Future<_i6.CustomerAccount?>.value(),
      ) as _i3.Future<_i6.CustomerAccount?>);

  @override
  _i3.Future<_i6.CustomerCreditInfo?> getCreditInfo(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCreditInfo,
          [customerId],
        ),
        returnValue: _i3.Future<_i6.CustomerCreditInfo?>.value(),
      ) as _i3.Future<_i6.CustomerCreditInfo?>);

  @override
  _i3.Future<_i6.CustomerPackagingInfo?> getPackagingInfo(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingInfo,
          [customerId],
        ),
        returnValue: _i3.Future<_i6.CustomerPackagingInfo?>.value(),
      ) as _i3.Future<_i6.CustomerPackagingInfo?>);

  @override
  _i3.Future<void> updateSettings(
    String? customerId,
    _i6.CustomerSettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSettings,
          [
            customerId,
            settings,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateContact(
    String? customerId,
    String? contactId,
    _i6.CustomerContact? contact,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContact,
          [
            customerId,
            contactId,
            contact,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> addContact(
    String? customerId,
    _i6.CustomerContact? contact,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addContact,
          [
            customerId,
            contact,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #addContact,
            [
              customerId,
              contact,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> deleteContact(
    String? customerId,
    String? contactId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteContact,
          [
            customerId,
            contactId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.CustomerNotification>> getNotifications({
    required String? customerId,
    _i8.NotificationType? type,
    bool? isRead,
    _i8.NotificationPriority? priority,
    DateTime? startDate,
    DateTime? endDate,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
          {
            #customerId: customerId,
            #type: type,
            #isRead: isRead,
            #priority: priority,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i8.CustomerNotification>>.value(
            <_i8.CustomerNotification>[]),
      ) as _i3.Future<List<_i8.CustomerNotification>>);

  @override
  _i3.Future<int> getUnreadNotificationsCount(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadNotificationsCount,
          [customerId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> markNotificationAsRead(
    String? customerId,
    String? notificationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markNotificationAsRead,
          [
            customerId,
            notificationId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> markAllNotificationsAsRead(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAllNotificationsAsRead,
          [customerId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> deleteNotification(
    String? customerId,
    String? notificationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotification,
          [
            customerId,
            notificationId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> deleteReadNotifications(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteReadNotifications,
          [customerId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Stream<_i8.CustomerNotification> subscribeToNotifications(
          String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToNotifications,
          [customerId],
        ),
        returnValue: _i3.Stream<_i8.CustomerNotification>.empty(),
      ) as _i3.Stream<_i8.CustomerNotification>);

  @override
  _i3.Future<void> syncCustomerData(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #syncCustomerData,
          [customerId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [customerId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> hasCachedData(String? customerId) => (super.noSuchMethod(
        Invocation.method(
          #hasCachedData,
          [customerId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
