// Mocks generated by Mockito 5.4.6 from annotations
// in awid_mobile/test/domain/usecases/manage_packaging_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:awid_mobile/features/deliverer/domain/entities/packaging_transaction.dart'
    as _i6;
import 'package:awid_mobile/features/deliverer/domain/entities/payment_collection.dart'
    as _i5;
import 'package:awid_mobile/features/deliverer/domain/entities/proof_of_delivery.dart'
    as _i4;
import 'package:awid_mobile/features/deliverer/domain/repositories/delivery_actions_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePackagingBalance_0 extends _i1.SmartFake
    implements _i2.PackagingBalance {
  _FakePackagingBalance_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDelivererEarnings_1 extends _i1.SmartFake
    implements _i2.DelivererEarnings {
  _FakeDelivererEarnings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDelivererDetailedStats_2 extends _i1.SmartFake
    implements _i2.DelivererDetailedStats {
  _FakeDelivererDetailedStats_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResult_3 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncStatus_4 extends _i1.SmartFake implements _i2.SyncStatus {
  _FakeSyncStatus_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DeliveryActionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeliveryActionsRepository extends _i1.Mock
    implements _i2.DeliveryActionsRepository {
  MockDeliveryActionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveProofOfDelivery(_i4.ProofOfDelivery? proof) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProofOfDelivery,
          [proof],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadProofOfDelivery(String? proofId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProofOfDelivery,
          [proofId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.ProofOfDelivery>> getProofsOfDelivery({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    bool? isUploaded,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProofsOfDelivery,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #isUploaded: isUploaded,
          },
        ),
        returnValue: _i3.Future<List<_i4.ProofOfDelivery>>.value(
            <_i4.ProofOfDelivery>[]),
      ) as _i3.Future<List<_i4.ProofOfDelivery>>);

  @override
  _i3.Future<_i4.ProofOfDelivery?> getProofOfDelivery(String? proofId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProofOfDelivery,
          [proofId],
        ),
        returnValue: _i3.Future<_i4.ProofOfDelivery?>.value(),
      ) as _i3.Future<_i4.ProofOfDelivery?>);

  @override
  _i3.Future<void> deleteProofOfDelivery(String? proofId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProofOfDelivery,
          [proofId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadPendingProofs(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPendingProofs,
          [delivererId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> savePaymentCollection(_i5.PaymentCollection? payment) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePaymentCollection,
          [payment],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadPaymentCollection(String? paymentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPaymentCollection,
          [paymentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.PaymentCollection>> getPaymentCollections({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    _i5.PaymentMode? mode,
    bool? isUploaded,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentCollections,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #mode: mode,
            #isUploaded: isUploaded,
          },
        ),
        returnValue: _i3.Future<List<_i5.PaymentCollection>>.value(
            <_i5.PaymentCollection>[]),
      ) as _i3.Future<List<_i5.PaymentCollection>>);

  @override
  _i3.Future<_i5.PaymentCollection?> getPaymentCollection(String? paymentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentCollection,
          [paymentId],
        ),
        returnValue: _i3.Future<_i5.PaymentCollection?>.value(),
      ) as _i3.Future<_i5.PaymentCollection?>);

  @override
  _i3.Future<void> deletePaymentCollection(String? paymentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePaymentCollection,
          [paymentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadPendingPayments(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPendingPayments,
          [delivererId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.UnpaidOrder>> getUnpaidOrders(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnpaidOrders,
          [customerId],
        ),
        returnValue:
            _i3.Future<List<_i2.UnpaidOrder>>.value(<_i2.UnpaidOrder>[]),
      ) as _i3.Future<List<_i2.UnpaidOrder>>);

  @override
  _i3.Future<List<_i5.PaymentAllocation>> calculateAutoAllocation({
    required String? customerId,
    required double? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateAutoAllocation,
          [],
          {
            #customerId: customerId,
            #amount: amount,
          },
        ),
        returnValue: _i3.Future<List<_i5.PaymentAllocation>>.value(
            <_i5.PaymentAllocation>[]),
      ) as _i3.Future<List<_i5.PaymentAllocation>>);

  @override
  _i3.Future<void> savePackagingTransaction(
          _i6.PackagingTransaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePackagingTransaction,
          [transaction],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadPackagingTransaction(String? transactionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPackagingTransaction,
          [transactionId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.PackagingTransaction>> getPackagingTransactions({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    _i6.PackagingTransactionType? type,
    bool? isUploaded,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingTransactions,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #type: type,
            #isUploaded: isUploaded,
          },
        ),
        returnValue: _i3.Future<List<_i6.PackagingTransaction>>.value(
            <_i6.PackagingTransaction>[]),
      ) as _i3.Future<List<_i6.PackagingTransaction>>);

  @override
  _i3.Future<_i6.PackagingTransaction?> getPackagingTransaction(
          String? transactionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingTransaction,
          [transactionId],
        ),
        returnValue: _i3.Future<_i6.PackagingTransaction?>.value(),
      ) as _i3.Future<_i6.PackagingTransaction?>);

  @override
  _i3.Future<void> deletePackagingTransaction(String? transactionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePackagingTransaction,
          [transactionId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadPendingTransactions(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPendingTransactions,
          [delivererId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.PackagingBalance> getPackagingBalance(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingBalance,
          [customerId],
        ),
        returnValue:
            _i3.Future<_i2.PackagingBalance>.value(_FakePackagingBalance_0(
          this,
          Invocation.method(
            #getPackagingBalance,
            [customerId],
          ),
        )),
      ) as _i3.Future<_i2.PackagingBalance>);

  @override
  _i3.Future<List<_i2.PackagingType>> getPackagingTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingTypes,
          [],
        ),
        returnValue:
            _i3.Future<List<_i2.PackagingType>>.value(<_i2.PackagingType>[]),
      ) as _i3.Future<List<_i2.PackagingType>>);

  @override
  _i3.Future<_i2.PackagingQrData?> scanPackagingQrCode(String? qrData) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanPackagingQrCode,
          [qrData],
        ),
        returnValue: _i3.Future<_i2.PackagingQrData?>.value(),
      ) as _i3.Future<_i2.PackagingQrData?>);

  @override
  _i3.Future<List<_i2.DeliveryHistoryItem>> getDeliveryHistory({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    String? status,
    String? customerId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeliveryHistory,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #status: status,
            #customerId: customerId,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i2.DeliveryHistoryItem>>.value(
            <_i2.DeliveryHistoryItem>[]),
      ) as _i3.Future<List<_i2.DeliveryHistoryItem>>);

  @override
  _i3.Future<_i2.DelivererEarnings> getDelivererEarnings({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDelivererEarnings,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i3.Future<_i2.DelivererEarnings>.value(_FakeDelivererEarnings_1(
          this,
          Invocation.method(
            #getDelivererEarnings,
            [],
            {
              #delivererId: delivererId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i3.Future<_i2.DelivererEarnings>);

  @override
  _i3.Future<_i2.DelivererDetailedStats> getDetailedStats({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailedStats,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i3.Future<_i2.DelivererDetailedStats>.value(
            _FakeDelivererDetailedStats_2(
          this,
          Invocation.method(
            #getDetailedStats,
            [],
            {
              #delivererId: delivererId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i3.Future<_i2.DelivererDetailedStats>);

  @override
  _i3.Future<_i2.SyncResult> syncAllPendingData(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncAllPendingData,
          [delivererId],
        ),
        returnValue: _i3.Future<_i2.SyncResult>.value(_FakeSyncResult_3(
          this,
          Invocation.method(
            #syncAllPendingData,
            [delivererId],
          ),
        )),
      ) as _i3.Future<_i2.SyncResult>);

  @override
  _i3.Future<_i2.SyncStatus> getSyncStatus(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncStatus,
          [delivererId],
        ),
        returnValue: _i3.Future<_i2.SyncStatus>.value(_FakeSyncStatus_4(
          this,
          Invocation.method(
            #getSyncStatus,
            [delivererId],
          ),
        )),
      ) as _i3.Future<_i2.SyncStatus>);

  @override
  _i3.Future<void> forceSyncAll(String? delivererId) => (super.noSuchMethod(
        Invocation.method(
          #forceSyncAll,
          [delivererId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
