// Mocks generated by Mockito 5.4.6 from annotations
// in awid_mobile/test/domain/usecases/update_order_status_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:awid_mobile/features/kitchen/domain/entities/kitchen_order.dart'
    as _i2;
import 'package:awid_mobile/features/kitchen/domain/entities/kitchen_station.dart'
    as _i3;
import 'package:awid_mobile/features/kitchen/domain/entities/kitchen_stats.dart'
    as _i5;
import 'package:awid_mobile/features/kitchen/domain/entities/production_task.dart'
    as _i6;
import 'package:awid_mobile/features/kitchen/domain/entities/stock_item.dart'
    as _i4;
import 'package:awid_mobile/features/kitchen/domain/repositories/kitchen_repository.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKitchenOrder_0 extends _i1.SmartFake implements _i2.KitchenOrder {
  _FakeKitchenOrder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKitchenStation_1 extends _i1.SmartFake
    implements _i3.KitchenStation {
  _FakeKitchenStation_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStockItem_2 extends _i1.SmartFake implements _i4.StockItem {
  _FakeStockItem_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKitchenStats_3 extends _i1.SmartFake implements _i5.KitchenStats {
  _FakeKitchenStats_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeriodStats_4 extends _i1.SmartFake implements _i5.PeriodStats {
  _FakePeriodStats_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductionTask_5 extends _i1.SmartFake
    implements _i6.ProductionTask {
  _FakeProductionTask_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KitchenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKitchenRepository extends _i1.Mock implements _i7.KitchenRepository {
  MockKitchenRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i2.KitchenOrder>> getOrders({
    _i2.KitchenOrderStatus? status,
    _i2.OrderPriority? priority,
    String? stationId,
    DateTime? date,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
          {
            #status: status,
            #priority: priority,
            #stationId: stationId,
            #date: date,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue:
            _i8.Future<List<_i2.KitchenOrder>>.value(<_i2.KitchenOrder>[]),
      ) as _i8.Future<List<_i2.KitchenOrder>>);

  @override
  _i8.Future<_i2.KitchenOrder> getOrderById(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderById,
          [orderId],
        ),
        returnValue: _i8.Future<_i2.KitchenOrder>.value(_FakeKitchenOrder_0(
          this,
          Invocation.method(
            #getOrderById,
            [orderId],
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrder>);

  @override
  _i8.Future<_i2.KitchenOrder> updateOrderStatus({
    required String? orderId,
    required _i2.KitchenOrderStatus? status,
    String? stationId,
    String? staffId,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatus,
          [],
          {
            #orderId: orderId,
            #status: status,
            #stationId: stationId,
            #staffId: staffId,
            #notes: notes,
          },
        ),
        returnValue: _i8.Future<_i2.KitchenOrder>.value(_FakeKitchenOrder_0(
          this,
          Invocation.method(
            #updateOrderStatus,
            [],
            {
              #orderId: orderId,
              #status: status,
              #stationId: stationId,
              #staffId: staffId,
              #notes: notes,
            },
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrder>);

  @override
  _i8.Future<_i2.KitchenOrder> assignOrderToStation({
    required String? orderId,
    required String? stationId,
    String? staffId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignOrderToStation,
          [],
          {
            #orderId: orderId,
            #stationId: stationId,
            #staffId: staffId,
          },
        ),
        returnValue: _i8.Future<_i2.KitchenOrder>.value(_FakeKitchenOrder_0(
          this,
          Invocation.method(
            #assignOrderToStation,
            [],
            {
              #orderId: orderId,
              #stationId: stationId,
              #staffId: staffId,
            },
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrder>);

  @override
  _i8.Future<_i2.KitchenOrder> updateOrderPriority({
    required String? orderId,
    required _i2.OrderPriority? priority,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderPriority,
          [],
          {
            #orderId: orderId,
            #priority: priority,
          },
        ),
        returnValue: _i8.Future<_i2.KitchenOrder>.value(_FakeKitchenOrder_0(
          this,
          Invocation.method(
            #updateOrderPriority,
            [],
            {
              #orderId: orderId,
              #priority: priority,
            },
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrder>);

  @override
  _i8.Future<_i2.KitchenOrder> updateOrderNotes({
    required String? orderId,
    required String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderNotes,
          [],
          {
            #orderId: orderId,
            #notes: notes,
          },
        ),
        returnValue: _i8.Future<_i2.KitchenOrder>.value(_FakeKitchenOrder_0(
          this,
          Invocation.method(
            #updateOrderNotes,
            [],
            {
              #orderId: orderId,
              #notes: notes,
            },
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrder>);

  @override
  _i8.Future<_i2.KitchenOrder> markItemPrepared({
    required String? orderId,
    required String? itemId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markItemPrepared,
          [],
          {
            #orderId: orderId,
            #itemId: itemId,
          },
        ),
        returnValue: _i8.Future<_i2.KitchenOrder>.value(_FakeKitchenOrder_0(
          this,
          Invocation.method(
            #markItemPrepared,
            [],
            {
              #orderId: orderId,
              #itemId: itemId,
            },
          ),
        )),
      ) as _i8.Future<_i2.KitchenOrder>);

  @override
  _i8.Future<List<_i3.KitchenStation>> getStations({
    _i3.StationType? type,
    _i3.StationStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStations,
          [],
          {
            #type: type,
            #status: status,
          },
        ),
        returnValue:
            _i8.Future<List<_i3.KitchenStation>>.value(<_i3.KitchenStation>[]),
      ) as _i8.Future<List<_i3.KitchenStation>>);

  @override
  _i8.Future<_i3.KitchenStation> getStationById(String? stationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStationById,
          [stationId],
        ),
        returnValue: _i8.Future<_i3.KitchenStation>.value(_FakeKitchenStation_1(
          this,
          Invocation.method(
            #getStationById,
            [stationId],
          ),
        )),
      ) as _i8.Future<_i3.KitchenStation>);

  @override
  _i8.Future<_i3.KitchenStation> updateStationStatus({
    required String? stationId,
    required _i3.StationStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStationStatus,
          [],
          {
            #stationId: stationId,
            #status: status,
          },
        ),
        returnValue: _i8.Future<_i3.KitchenStation>.value(_FakeKitchenStation_1(
          this,
          Invocation.method(
            #updateStationStatus,
            [],
            {
              #stationId: stationId,
              #status: status,
            },
          ),
        )),
      ) as _i8.Future<_i3.KitchenStation>);

  @override
  _i8.Future<_i3.KitchenStation> assignStaffToStation({
    required String? stationId,
    required String? staffId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignStaffToStation,
          [],
          {
            #stationId: stationId,
            #staffId: staffId,
          },
        ),
        returnValue: _i8.Future<_i3.KitchenStation>.value(_FakeKitchenStation_1(
          this,
          Invocation.method(
            #assignStaffToStation,
            [],
            {
              #stationId: stationId,
              #staffId: staffId,
            },
          ),
        )),
      ) as _i8.Future<_i3.KitchenStation>);

  @override
  _i8.Future<List<_i4.StockItem>> getStockItems({
    String? category,
    _i4.StockLevel? level,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockItems,
          [],
          {
            #category: category,
            #level: level,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue: _i8.Future<List<_i4.StockItem>>.value(<_i4.StockItem>[]),
      ) as _i8.Future<List<_i4.StockItem>>);

  @override
  _i8.Future<_i4.StockItem> getStockItemById(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockItemById,
          [itemId],
        ),
        returnValue: _i8.Future<_i4.StockItem>.value(_FakeStockItem_2(
          this,
          Invocation.method(
            #getStockItemById,
            [itemId],
          ),
        )),
      ) as _i8.Future<_i4.StockItem>);

  @override
  _i8.Future<_i4.StockItem> adjustStockQuantity({
    required String? itemId,
    required double? quantity,
    required _i4.StockMovementType? type,
    String? reason,
    String? orderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adjustStockQuantity,
          [],
          {
            #itemId: itemId,
            #quantity: quantity,
            #type: type,
            #reason: reason,
            #orderId: orderId,
          },
        ),
        returnValue: _i8.Future<_i4.StockItem>.value(_FakeStockItem_2(
          this,
          Invocation.method(
            #adjustStockQuantity,
            [],
            {
              #itemId: itemId,
              #quantity: quantity,
              #type: type,
              #reason: reason,
              #orderId: orderId,
            },
          ),
        )),
      ) as _i8.Future<_i4.StockItem>);

  @override
  _i8.Future<_i4.StockItem> createStockItem({
    required String? productId,
    required String? productName,
    required double? currentQuantity,
    required double? minimumQuantity,
    required double? maximumQuantity,
    required _i4.StockUnit? unit,
    String? category,
    String? supplier,
    String? location,
    String? barcode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStockItem,
          [],
          {
            #productId: productId,
            #productName: productName,
            #currentQuantity: currentQuantity,
            #minimumQuantity: minimumQuantity,
            #maximumQuantity: maximumQuantity,
            #unit: unit,
            #category: category,
            #supplier: supplier,
            #location: location,
            #barcode: barcode,
          },
        ),
        returnValue: _i8.Future<_i4.StockItem>.value(_FakeStockItem_2(
          this,
          Invocation.method(
            #createStockItem,
            [],
            {
              #productId: productId,
              #productName: productName,
              #currentQuantity: currentQuantity,
              #minimumQuantity: minimumQuantity,
              #maximumQuantity: maximumQuantity,
              #unit: unit,
              #category: category,
              #supplier: supplier,
              #location: location,
              #barcode: barcode,
            },
          ),
        )),
      ) as _i8.Future<_i4.StockItem>);

  @override
  _i8.Future<_i4.StockItem> updateStockItem({
    required String? itemId,
    double? minimumQuantity,
    double? maximumQuantity,
    String? location,
    String? supplier,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStockItem,
          [],
          {
            #itemId: itemId,
            #minimumQuantity: minimumQuantity,
            #maximumQuantity: maximumQuantity,
            #location: location,
            #supplier: supplier,
          },
        ),
        returnValue: _i8.Future<_i4.StockItem>.value(_FakeStockItem_2(
          this,
          Invocation.method(
            #updateStockItem,
            [],
            {
              #itemId: itemId,
              #minimumQuantity: minimumQuantity,
              #maximumQuantity: maximumQuantity,
              #location: location,
              #supplier: supplier,
            },
          ),
        )),
      ) as _i8.Future<_i4.StockItem>);

  @override
  _i8.Future<List<_i4.StockMovement>> getStockMovements({
    String? itemId,
    DateTime? startDate,
    DateTime? endDate,
    _i4.StockMovementType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockMovements,
          [],
          {
            #itemId: itemId,
            #startDate: startDate,
            #endDate: endDate,
            #type: type,
          },
        ),
        returnValue:
            _i8.Future<List<_i4.StockMovement>>.value(<_i4.StockMovement>[]),
      ) as _i8.Future<List<_i4.StockMovement>>);

  @override
  _i8.Future<List<_i4.StockAlert>> getStockAlerts({bool? activeOnly = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockAlerts,
          [],
          {#activeOnly: activeOnly},
        ),
        returnValue: _i8.Future<List<_i4.StockAlert>>.value(<_i4.StockAlert>[]),
      ) as _i8.Future<List<_i4.StockAlert>>);

  @override
  _i8.Future<void> resolveStockAlert(String? alertId) => (super.noSuchMethod(
        Invocation.method(
          #resolveStockAlert,
          [alertId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.KitchenStats> getStats({
    DateTime? date,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
          {
            #date: date,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue: _i8.Future<_i5.KitchenStats>.value(_FakeKitchenStats_3(
          this,
          Invocation.method(
            #getStats,
            [],
            {
              #date: date,
              #forceRefresh: forceRefresh,
            },
          ),
        )),
      ) as _i8.Future<_i5.KitchenStats>);

  @override
  _i8.Future<_i5.PeriodStats> getPeriodStats({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPeriodStats,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i8.Future<_i5.PeriodStats>.value(_FakePeriodStats_4(
          this,
          Invocation.method(
            #getPeriodStats,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i8.Future<_i5.PeriodStats>);

  @override
  _i8.Future<List<_i5.HourlyStats>> getHourlyStats({DateTime? date}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHourlyStats,
          [],
          {#date: date},
        ),
        returnValue:
            _i8.Future<List<_i5.HourlyStats>>.value(<_i5.HourlyStats>[]),
      ) as _i8.Future<List<_i5.HourlyStats>>);

  @override
  _i8.Future<List<_i6.ProductionTask>> getProductionTasks({
    _i6.TaskStatus? status,
    _i6.TaskType? type,
    String? stationId,
    DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductionTasks,
          [],
          {
            #status: status,
            #type: type,
            #stationId: stationId,
            #date: date,
          },
        ),
        returnValue:
            _i8.Future<List<_i6.ProductionTask>>.value(<_i6.ProductionTask>[]),
      ) as _i8.Future<List<_i6.ProductionTask>>);

  @override
  _i8.Future<_i6.ProductionTask> getTaskById(String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [taskId],
        ),
        returnValue: _i8.Future<_i6.ProductionTask>.value(_FakeProductionTask_5(
          this,
          Invocation.method(
            #getTaskById,
            [taskId],
          ),
        )),
      ) as _i8.Future<_i6.ProductionTask>);

  @override
  _i8.Future<_i6.ProductionTask> updateTaskStatus({
    required String? taskId,
    required _i6.TaskStatus? status,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTaskStatus,
          [],
          {
            #taskId: taskId,
            #status: status,
            #notes: notes,
          },
        ),
        returnValue: _i8.Future<_i6.ProductionTask>.value(_FakeProductionTask_5(
          this,
          Invocation.method(
            #updateTaskStatus,
            [],
            {
              #taskId: taskId,
              #status: status,
              #notes: notes,
            },
          ),
        )),
      ) as _i8.Future<_i6.ProductionTask>);

  @override
  _i8.Future<_i6.ProductionTask> assignTask({
    required String? taskId,
    required String? stationId,
    String? staffId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignTask,
          [],
          {
            #taskId: taskId,
            #stationId: stationId,
            #staffId: staffId,
          },
        ),
        returnValue: _i8.Future<_i6.ProductionTask>.value(_FakeProductionTask_5(
          this,
          Invocation.method(
            #assignTask,
            [],
            {
              #taskId: taskId,
              #stationId: stationId,
              #staffId: staffId,
            },
          ),
        )),
      ) as _i8.Future<_i6.ProductionTask>);

  @override
  _i8.Future<_i6.ProductionTask> completeTaskStep({
    required String? taskId,
    required String? stepId,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTaskStep,
          [],
          {
            #taskId: taskId,
            #stepId: stepId,
            #notes: notes,
          },
        ),
        returnValue: _i8.Future<_i6.ProductionTask>.value(_FakeProductionTask_5(
          this,
          Invocation.method(
            #completeTaskStep,
            [],
            {
              #taskId: taskId,
              #stepId: stepId,
              #notes: notes,
            },
          ),
        )),
      ) as _i8.Future<_i6.ProductionTask>);

  @override
  _i8.Stream<_i2.KitchenOrder> watchOrderUpdates() => (super.noSuchMethod(
        Invocation.method(
          #watchOrderUpdates,
          [],
        ),
        returnValue: _i8.Stream<_i2.KitchenOrder>.empty(),
      ) as _i8.Stream<_i2.KitchenOrder>);

  @override
  _i8.Stream<_i4.StockAlert> watchStockAlerts() => (super.noSuchMethod(
        Invocation.method(
          #watchStockAlerts,
          [],
        ),
        returnValue: _i8.Stream<_i4.StockAlert>.empty(),
      ) as _i8.Stream<_i4.StockAlert>);

  @override
  _i8.Stream<_i5.KitchenStats> watchStats() => (super.noSuchMethod(
        Invocation.method(
          #watchStats,
          [],
        ),
        returnValue: _i8.Stream<_i5.KitchenStats>.empty(),
      ) as _i8.Stream<_i5.KitchenStats>);
}
