// Mocks generated by Mockito 5.4.6 from annotations
// in awid_mobile/test/presentation/providers/customer_orders_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:awid_mobile/features/customer/domain/usecases/get_orders_usecase.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetOrdersResult_0 extends _i1.SmartFake
    implements _i2.GetOrdersResult {
  _FakeGetOrdersResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetOrderResult_1 extends _i1.SmartFake
    implements _i2.GetOrderResult {
  _FakeGetOrderResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetOrdersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOrdersUseCase extends _i1.Mock implements _i2.GetOrdersUseCase {
  MockGetOrdersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.GetOrdersResult> execute(_i2.GetOrdersParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [params],
        ),
        returnValue:
            _i3.Future<_i2.GetOrdersResult>.value(_FakeGetOrdersResult_0(
          this,
          Invocation.method(
            #execute,
            [params],
          ),
        )),
      ) as _i3.Future<_i2.GetOrdersResult>);

  @override
  _i3.Future<_i2.GetOrderResult> getOrder(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [orderId],
        ),
        returnValue: _i3.Future<_i2.GetOrderResult>.value(_FakeGetOrderResult_1(
          this,
          Invocation.method(
            #getOrder,
            [orderId],
          ),
        )),
      ) as _i3.Future<_i2.GetOrderResult>);

  @override
  _i3.Future<_i2.GetOrdersResult> getActiveOrders(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveOrders,
          [customerId],
        ),
        returnValue:
            _i3.Future<_i2.GetOrdersResult>.value(_FakeGetOrdersResult_0(
          this,
          Invocation.method(
            #getActiveOrders,
            [customerId],
          ),
        )),
      ) as _i3.Future<_i2.GetOrdersResult>);

  @override
  _i3.Future<_i2.GetOrdersResult> getOrderHistory(
    String? customerId, {
    DateTime? startDate,
    DateTime? endDate,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderHistory,
          [customerId],
          {
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue:
            _i3.Future<_i2.GetOrdersResult>.value(_FakeGetOrdersResult_0(
          this,
          Invocation.method(
            #getOrderHistory,
            [customerId],
            {
              #startDate: startDate,
              #endDate: endDate,
              #limit: limit,
            },
          ),
        )),
      ) as _i3.Future<_i2.GetOrdersResult>);

  @override
  _i3.Future<_i2.GetOrdersResult> searchOrders(
    String? customerId,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchOrders,
          [
            customerId,
            query,
          ],
        ),
        returnValue:
            _i3.Future<_i2.GetOrdersResult>.value(_FakeGetOrdersResult_0(
          this,
          Invocation.method(
            #searchOrders,
            [
              customerId,
              query,
            ],
          ),
        )),
      ) as _i3.Future<_i2.GetOrdersResult>);
}
