// Mocks generated by Mockito 5.4.6 from annotations
// in awid_mobile/test/presentation/providers/delivery_actions_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:awid_mobile/features/deliverer/domain/entities/packaging_transaction.dart'
    as _i8;
import 'package:awid_mobile/features/deliverer/domain/entities/payment_collection.dart'
    as _i7;
import 'package:awid_mobile/features/deliverer/domain/entities/proof_of_delivery.dart'
    as _i9;
import 'package:awid_mobile/features/deliverer/domain/repositories/delivery_actions_repository.dart'
    as _i5;
import 'package:awid_mobile/features/deliverer/domain/usecases/collect_payment_usecase.dart'
    as _i3;
import 'package:awid_mobile/features/deliverer/domain/usecases/complete_delivery_usecase.dart'
    as _i2;
import 'package:awid_mobile/features/deliverer/domain/usecases/manage_packaging_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCompleteDeliveryResult_0 extends _i1.SmartFake
    implements _i2.CompleteDeliveryResult {
  _FakeCompleteDeliveryResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectPaymentResult_1 extends _i1.SmartFake
    implements _i3.CollectPaymentResult {
  _FakeCollectPaymentResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeManagePackagingResult_2 extends _i1.SmartFake
    implements _i4.ManagePackagingResult {
  _FakeManagePackagingResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePackagingQrResult_3 extends _i1.SmartFake
    implements _i4.PackagingQrResult {
  _FakePackagingQrResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePackagingBalance_4 extends _i1.SmartFake
    implements _i5.PackagingBalance {
  _FakePackagingBalance_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDelivererEarnings_5 extends _i1.SmartFake
    implements _i5.DelivererEarnings {
  _FakeDelivererEarnings_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDelivererDetailedStats_6 extends _i1.SmartFake
    implements _i5.DelivererDetailedStats {
  _FakeDelivererDetailedStats_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResult_7 extends _i1.SmartFake implements _i5.SyncResult {
  _FakeSyncResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncStatus_8 extends _i1.SmartFake implements _i5.SyncStatus {
  _FakeSyncStatus_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CompleteDeliveryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompleteDeliveryUseCase extends _i1.Mock
    implements _i2.CompleteDeliveryUseCase {
  MockCompleteDeliveryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.CompleteDeliveryResult> execute(
          _i2.CompleteDeliveryParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [params],
        ),
        returnValue: _i6.Future<_i2.CompleteDeliveryResult>.value(
            _FakeCompleteDeliveryResult_0(
          this,
          Invocation.method(
            #execute,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.CompleteDeliveryResult>);
}

/// A class which mocks [CollectPaymentUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCollectPaymentUseCase extends _i1.Mock
    implements _i3.CollectPaymentUseCase {
  MockCollectPaymentUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.CollectPaymentResult> executeAutoAllocation(
          _i3.CollectPaymentAutoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeAutoAllocation,
          [params],
        ),
        returnValue: _i6.Future<_i3.CollectPaymentResult>.value(
            _FakeCollectPaymentResult_1(
          this,
          Invocation.method(
            #executeAutoAllocation,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.CollectPaymentResult>);

  @override
  _i6.Future<_i3.CollectPaymentResult> executeManualAllocation(
          _i3.CollectPaymentManualParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeManualAllocation,
          [params],
        ),
        returnValue: _i6.Future<_i3.CollectPaymentResult>.value(
            _FakeCollectPaymentResult_1(
          this,
          Invocation.method(
            #executeManualAllocation,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.CollectPaymentResult>);

  @override
  _i6.Future<List<_i5.UnpaidOrder>> getUnpaidOrders(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnpaidOrders,
          [customerId],
        ),
        returnValue:
            _i6.Future<List<_i5.UnpaidOrder>>.value(<_i5.UnpaidOrder>[]),
      ) as _i6.Future<List<_i5.UnpaidOrder>>);

  @override
  _i6.Future<List<_i7.PaymentAllocation>> calculateAllocationProposal({
    required String? customerId,
    required double? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateAllocationProposal,
          [],
          {
            #customerId: customerId,
            #amount: amount,
          },
        ),
        returnValue: _i6.Future<List<_i7.PaymentAllocation>>.value(
            <_i7.PaymentAllocation>[]),
      ) as _i6.Future<List<_i7.PaymentAllocation>>);
}

/// A class which mocks [ManagePackagingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockManagePackagingUseCase extends _i1.Mock
    implements _i4.ManagePackagingUseCase {
  MockManagePackagingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.ManagePackagingResult> recordDeposit(
          _i4.PackagingDepositParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordDeposit,
          [params],
        ),
        returnValue: _i6.Future<_i4.ManagePackagingResult>.value(
            _FakeManagePackagingResult_2(
          this,
          Invocation.method(
            #recordDeposit,
            [params],
          ),
        )),
      ) as _i6.Future<_i4.ManagePackagingResult>);

  @override
  _i6.Future<_i4.ManagePackagingResult> recordReturn(
          _i4.PackagingReturnParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordReturn,
          [params],
        ),
        returnValue: _i6.Future<_i4.ManagePackagingResult>.value(
            _FakeManagePackagingResult_2(
          this,
          Invocation.method(
            #recordReturn,
            [params],
          ),
        )),
      ) as _i6.Future<_i4.ManagePackagingResult>);

  @override
  _i6.Future<_i4.PackagingQrResult> scanQrCode(String? qrData) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanQrCode,
          [qrData],
        ),
        returnValue:
            _i6.Future<_i4.PackagingQrResult>.value(_FakePackagingQrResult_3(
          this,
          Invocation.method(
            #scanQrCode,
            [qrData],
          ),
        )),
      ) as _i6.Future<_i4.PackagingQrResult>);

  @override
  _i6.Future<_i5.PackagingBalance> getPackagingBalance(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingBalance,
          [customerId],
        ),
        returnValue:
            _i6.Future<_i5.PackagingBalance>.value(_FakePackagingBalance_4(
          this,
          Invocation.method(
            #getPackagingBalance,
            [customerId],
          ),
        )),
      ) as _i6.Future<_i5.PackagingBalance>);

  @override
  _i6.Future<List<_i5.PackagingType>> getPackagingTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingTypes,
          [],
        ),
        returnValue:
            _i6.Future<List<_i5.PackagingType>>.value(<_i5.PackagingType>[]),
      ) as _i6.Future<List<_i5.PackagingType>>);

  @override
  _i6.Future<List<_i8.PackagingTransaction>> getTransactionHistory({
    required String? delivererId,
    String? customerId,
    DateTime? startDate,
    DateTime? endDate,
    _i8.PackagingTransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionHistory,
          [],
          {
            #delivererId: delivererId,
            #customerId: customerId,
            #startDate: startDate,
            #endDate: endDate,
            #type: type,
          },
        ),
        returnValue: _i6.Future<List<_i8.PackagingTransaction>>.value(
            <_i8.PackagingTransaction>[]),
      ) as _i6.Future<List<_i8.PackagingTransaction>>);
}

/// A class which mocks [DeliveryActionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeliveryActionsRepository extends _i1.Mock
    implements _i5.DeliveryActionsRepository {
  MockDeliveryActionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveProofOfDelivery(_i9.ProofOfDelivery? proof) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProofOfDelivery,
          [proof],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> uploadProofOfDelivery(String? proofId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProofOfDelivery,
          [proofId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.ProofOfDelivery>> getProofsOfDelivery({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    bool? isUploaded,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProofsOfDelivery,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #isUploaded: isUploaded,
          },
        ),
        returnValue: _i6.Future<List<_i9.ProofOfDelivery>>.value(
            <_i9.ProofOfDelivery>[]),
      ) as _i6.Future<List<_i9.ProofOfDelivery>>);

  @override
  _i6.Future<_i9.ProofOfDelivery?> getProofOfDelivery(String? proofId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProofOfDelivery,
          [proofId],
        ),
        returnValue: _i6.Future<_i9.ProofOfDelivery?>.value(),
      ) as _i6.Future<_i9.ProofOfDelivery?>);

  @override
  _i6.Future<void> deleteProofOfDelivery(String? proofId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProofOfDelivery,
          [proofId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> uploadPendingProofs(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPendingProofs,
          [delivererId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> savePaymentCollection(_i7.PaymentCollection? payment) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePaymentCollection,
          [payment],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> uploadPaymentCollection(String? paymentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPaymentCollection,
          [paymentId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.PaymentCollection>> getPaymentCollections({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    _i7.PaymentMode? mode,
    bool? isUploaded,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentCollections,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #mode: mode,
            #isUploaded: isUploaded,
          },
        ),
        returnValue: _i6.Future<List<_i7.PaymentCollection>>.value(
            <_i7.PaymentCollection>[]),
      ) as _i6.Future<List<_i7.PaymentCollection>>);

  @override
  _i6.Future<_i7.PaymentCollection?> getPaymentCollection(String? paymentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentCollection,
          [paymentId],
        ),
        returnValue: _i6.Future<_i7.PaymentCollection?>.value(),
      ) as _i6.Future<_i7.PaymentCollection?>);

  @override
  _i6.Future<void> deletePaymentCollection(String? paymentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePaymentCollection,
          [paymentId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> uploadPendingPayments(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPendingPayments,
          [delivererId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i5.UnpaidOrder>> getUnpaidOrders(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnpaidOrders,
          [customerId],
        ),
        returnValue:
            _i6.Future<List<_i5.UnpaidOrder>>.value(<_i5.UnpaidOrder>[]),
      ) as _i6.Future<List<_i5.UnpaidOrder>>);

  @override
  _i6.Future<List<_i7.PaymentAllocation>> calculateAutoAllocation({
    required String? customerId,
    required double? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateAutoAllocation,
          [],
          {
            #customerId: customerId,
            #amount: amount,
          },
        ),
        returnValue: _i6.Future<List<_i7.PaymentAllocation>>.value(
            <_i7.PaymentAllocation>[]),
      ) as _i6.Future<List<_i7.PaymentAllocation>>);

  @override
  _i6.Future<void> savePackagingTransaction(
          _i8.PackagingTransaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePackagingTransaction,
          [transaction],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> uploadPackagingTransaction(String? transactionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPackagingTransaction,
          [transactionId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.PackagingTransaction>> getPackagingTransactions({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    _i8.PackagingTransactionType? type,
    bool? isUploaded,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingTransactions,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #type: type,
            #isUploaded: isUploaded,
          },
        ),
        returnValue: _i6.Future<List<_i8.PackagingTransaction>>.value(
            <_i8.PackagingTransaction>[]),
      ) as _i6.Future<List<_i8.PackagingTransaction>>);

  @override
  _i6.Future<_i8.PackagingTransaction?> getPackagingTransaction(
          String? transactionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingTransaction,
          [transactionId],
        ),
        returnValue: _i6.Future<_i8.PackagingTransaction?>.value(),
      ) as _i6.Future<_i8.PackagingTransaction?>);

  @override
  _i6.Future<void> deletePackagingTransaction(String? transactionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePackagingTransaction,
          [transactionId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> uploadPendingTransactions(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPendingTransactions,
          [delivererId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i5.PackagingBalance> getPackagingBalance(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingBalance,
          [customerId],
        ),
        returnValue:
            _i6.Future<_i5.PackagingBalance>.value(_FakePackagingBalance_4(
          this,
          Invocation.method(
            #getPackagingBalance,
            [customerId],
          ),
        )),
      ) as _i6.Future<_i5.PackagingBalance>);

  @override
  _i6.Future<List<_i5.PackagingType>> getPackagingTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagingTypes,
          [],
        ),
        returnValue:
            _i6.Future<List<_i5.PackagingType>>.value(<_i5.PackagingType>[]),
      ) as _i6.Future<List<_i5.PackagingType>>);

  @override
  _i6.Future<_i5.PackagingQrData?> scanPackagingQrCode(String? qrData) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanPackagingQrCode,
          [qrData],
        ),
        returnValue: _i6.Future<_i5.PackagingQrData?>.value(),
      ) as _i6.Future<_i5.PackagingQrData?>);

  @override
  _i6.Future<List<_i5.DeliveryHistoryItem>> getDeliveryHistory({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
    String? status,
    String? customerId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeliveryHistory,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
            #status: status,
            #customerId: customerId,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i6.Future<List<_i5.DeliveryHistoryItem>>.value(
            <_i5.DeliveryHistoryItem>[]),
      ) as _i6.Future<List<_i5.DeliveryHistoryItem>>);

  @override
  _i6.Future<_i5.DelivererEarnings> getDelivererEarnings({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDelivererEarnings,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i6.Future<_i5.DelivererEarnings>.value(_FakeDelivererEarnings_5(
          this,
          Invocation.method(
            #getDelivererEarnings,
            [],
            {
              #delivererId: delivererId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i6.Future<_i5.DelivererEarnings>);

  @override
  _i6.Future<_i5.DelivererDetailedStats> getDetailedStats({
    required String? delivererId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailedStats,
          [],
          {
            #delivererId: delivererId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i6.Future<_i5.DelivererDetailedStats>.value(
            _FakeDelivererDetailedStats_6(
          this,
          Invocation.method(
            #getDetailedStats,
            [],
            {
              #delivererId: delivererId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i6.Future<_i5.DelivererDetailedStats>);

  @override
  _i6.Future<_i5.SyncResult> syncAllPendingData(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncAllPendingData,
          [delivererId],
        ),
        returnValue: _i6.Future<_i5.SyncResult>.value(_FakeSyncResult_7(
          this,
          Invocation.method(
            #syncAllPendingData,
            [delivererId],
          ),
        )),
      ) as _i6.Future<_i5.SyncResult>);

  @override
  _i6.Future<_i5.SyncStatus> getSyncStatus(String? delivererId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncStatus,
          [delivererId],
        ),
        returnValue: _i6.Future<_i5.SyncStatus>.value(_FakeSyncStatus_8(
          this,
          Invocation.method(
            #getSyncStatus,
            [delivererId],
          ),
        )),
      ) as _i6.Future<_i5.SyncStatus>);

  @override
  _i6.Future<void> forceSyncAll(String? delivererId) => (super.noSuchMethod(
        Invocation.method(
          #forceSyncAll,
          [delivererId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
