// Mocks generated by Mockito 5.4.6 from annotations
// in awid_mobile/test/presentation/providers/kitchen_orders_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:awid_mobile/features/kitchen/domain/entities/kitchen_order.dart'
    as _i4;
import 'package:awid_mobile/features/kitchen/domain/usecases/get_kitchen_orders_usecase.dart'
    as _i2;
import 'package:awid_mobile/features/kitchen/domain/usecases/update_order_status_usecase.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetKitchenOrdersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetKitchenOrdersUseCase extends _i1.Mock
    implements _i2.GetKitchenOrdersUseCase {
  MockGetKitchenOrdersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Result<List<_i4.KitchenOrder>>> execute({
    _i4.KitchenOrderStatus? status,
    _i4.OrderPriority? priority,
    String? stationId,
    DateTime? date,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #status: status,
            #priority: priority,
            #stationId: stationId,
            #date: date,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue: _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>.value(
            _FakeResult_0<List<_i4.KitchenOrder>>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #status: status,
              #priority: priority,
              #stationId: stationId,
              #date: date,
              #forceRefresh: forceRefresh,
            },
          ),
        )),
      ) as _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>);

  @override
  _i3.Future<_i2.Result<_i4.KitchenOrder>> getById(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [orderId],
        ),
        returnValue: _i3.Future<_i2.Result<_i4.KitchenOrder>>.value(
            _FakeResult_0<_i4.KitchenOrder>(
          this,
          Invocation.method(
            #getById,
            [orderId],
          ),
        )),
      ) as _i3.Future<_i2.Result<_i4.KitchenOrder>>);

  @override
  _i3.Future<_i2.Result<List<_i4.KitchenOrder>>> getPendingOrders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingOrders,
          [],
        ),
        returnValue: _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>.value(
            _FakeResult_0<List<_i4.KitchenOrder>>(
          this,
          Invocation.method(
            #getPendingOrders,
            [],
          ),
        )),
      ) as _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>);

  @override
  _i3.Future<_i2.Result<List<_i4.KitchenOrder>>> getActiveOrders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveOrders,
          [],
        ),
        returnValue: _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>.value(
            _FakeResult_0<List<_i4.KitchenOrder>>(
          this,
          Invocation.method(
            #getActiveOrders,
            [],
          ),
        )),
      ) as _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>);

  @override
  _i3.Future<_i2.Result<List<_i4.KitchenOrder>>> getReadyOrders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadyOrders,
          [],
        ),
        returnValue: _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>.value(
            _FakeResult_0<List<_i4.KitchenOrder>>(
          this,
          Invocation.method(
            #getReadyOrders,
            [],
          ),
        )),
      ) as _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>);

  @override
  _i3.Future<_i2.Result<List<_i4.KitchenOrder>>> getUrgentOrders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUrgentOrders,
          [],
        ),
        returnValue: _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>.value(
            _FakeResult_0<List<_i4.KitchenOrder>>(
          this,
          Invocation.method(
            #getUrgentOrders,
            [],
          ),
        )),
      ) as _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>);

  @override
  _i3.Future<_i2.Result<List<_i4.KitchenOrder>>> getDelayedOrders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDelayedOrders,
          [],
        ),
        returnValue: _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>.value(
            _FakeResult_0<List<_i4.KitchenOrder>>(
          this,
          Invocation.method(
            #getDelayedOrders,
            [],
          ),
        )),
      ) as _i3.Future<_i2.Result<List<_i4.KitchenOrder>>>);
}

/// A class which mocks [UpdateOrderStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateOrderStatusUseCase extends _i1.Mock
    implements _i5.UpdateOrderStatusUseCase {
  MockUpdateOrderStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Result<_i4.KitchenOrder>> execute({
    required String? orderId,
    required _i4.KitchenOrderStatus? newStatus,
    String? stationId,
    String? staffId,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #orderId: orderId,
            #newStatus: newStatus,
            #stationId: stationId,
            #staffId: staffId,
            #notes: notes,
          },
        ),
        returnValue: _i3.Future<_i2.Result<_i4.KitchenOrder>>.value(
            _FakeResult_0<_i4.KitchenOrder>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #orderId: orderId,
              #newStatus: newStatus,
              #stationId: stationId,
              #staffId: staffId,
              #notes: notes,
            },
          ),
        )),
      ) as _i3.Future<_i2.Result<_i4.KitchenOrder>>);

  @override
  _i3.Future<_i2.Result<_i4.KitchenOrder>> startPreparation({
    required String? orderId,
    String? stationId,
    String? staffId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPreparation,
          [],
          {
            #orderId: orderId,
            #stationId: stationId,
            #staffId: staffId,
          },
        ),
        returnValue: _i3.Future<_i2.Result<_i4.KitchenOrder>>.value(
            _FakeResult_0<_i4.KitchenOrder>(
          this,
          Invocation.method(
            #startPreparation,
            [],
            {
              #orderId: orderId,
              #stationId: stationId,
              #staffId: staffId,
            },
          ),
        )),
      ) as _i3.Future<_i2.Result<_i4.KitchenOrder>>);

  @override
  _i3.Future<_i2.Result<_i4.KitchenOrder>> markAsReady({
    required String? orderId,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsReady,
          [],
          {
            #orderId: orderId,
            #notes: notes,
          },
        ),
        returnValue: _i3.Future<_i2.Result<_i4.KitchenOrder>>.value(
            _FakeResult_0<_i4.KitchenOrder>(
          this,
          Invocation.method(
            #markAsReady,
            [],
            {
              #orderId: orderId,
              #notes: notes,
            },
          ),
        )),
      ) as _i3.Future<_i2.Result<_i4.KitchenOrder>>);

  @override
  _i3.Future<_i2.Result<_i4.KitchenOrder>> complete({
    required String? orderId,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #complete,
          [],
          {
            #orderId: orderId,
            #notes: notes,
          },
        ),
        returnValue: _i3.Future<_i2.Result<_i4.KitchenOrder>>.value(
            _FakeResult_0<_i4.KitchenOrder>(
          this,
          Invocation.method(
            #complete,
            [],
            {
              #orderId: orderId,
              #notes: notes,
            },
          ),
        )),
      ) as _i3.Future<_i2.Result<_i4.KitchenOrder>>);

  @override
  _i3.Future<_i2.Result<_i4.KitchenOrder>> cancel({
    required String? orderId,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
          {
            #orderId: orderId,
            #reason: reason,
          },
        ),
        returnValue: _i3.Future<_i2.Result<_i4.KitchenOrder>>.value(
            _FakeResult_0<_i4.KitchenOrder>(
          this,
          Invocation.method(
            #cancel,
            [],
            {
              #orderId: orderId,
              #reason: reason,
            },
          ),
        )),
      ) as _i3.Future<_i2.Result<_i4.KitchenOrder>>);

  @override
  _i3.Future<_i2.Result<_i4.KitchenOrder>> assignToStation({
    required String? orderId,
    required String? stationId,
    String? staffId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignToStation,
          [],
          {
            #orderId: orderId,
            #stationId: stationId,
            #staffId: staffId,
          },
        ),
        returnValue: _i3.Future<_i2.Result<_i4.KitchenOrder>>.value(
            _FakeResult_0<_i4.KitchenOrder>(
          this,
          Invocation.method(
            #assignToStation,
            [],
            {
              #orderId: orderId,
              #stationId: stationId,
              #staffId: staffId,
            },
          ),
        )),
      ) as _i3.Future<_i2.Result<_i4.KitchenOrder>>);

  @override
  _i3.Future<_i2.Result<_i4.KitchenOrder>> changePriority({
    required String? orderId,
    required _i4.OrderPriority? priority,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePriority,
          [],
          {
            #orderId: orderId,
            #priority: priority,
          },
        ),
        returnValue: _i3.Future<_i2.Result<_i4.KitchenOrder>>.value(
            _FakeResult_0<_i4.KitchenOrder>(
          this,
          Invocation.method(
            #changePriority,
            [],
            {
              #orderId: orderId,
              #priority: priority,
            },
          ),
        )),
      ) as _i3.Future<_i2.Result<_i4.KitchenOrder>>);

  @override
  _i3.Future<_i2.Result<_i4.KitchenOrder>> updateNotes({
    required String? orderId,
    required String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotes,
          [],
          {
            #orderId: orderId,
            #notes: notes,
          },
        ),
        returnValue: _i3.Future<_i2.Result<_i4.KitchenOrder>>.value(
            _FakeResult_0<_i4.KitchenOrder>(
          this,
          Invocation.method(
            #updateNotes,
            [],
            {
              #orderId: orderId,
              #notes: notes,
            },
          ),
        )),
      ) as _i3.Future<_i2.Result<_i4.KitchenOrder>>);

  @override
  _i3.Future<_i2.Result<_i4.KitchenOrder>> markItemPrepared({
    required String? orderId,
    required String? itemId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markItemPrepared,
          [],
          {
            #orderId: orderId,
            #itemId: itemId,
          },
        ),
        returnValue: _i3.Future<_i2.Result<_i4.KitchenOrder>>.value(
            _FakeResult_0<_i4.KitchenOrder>(
          this,
          Invocation.method(
            #markItemPrepared,
            [],
            {
              #orderId: orderId,
              #itemId: itemId,
            },
          ),
        )),
      ) as _i3.Future<_i2.Result<_i4.KitchenOrder>>);
}
