include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Erreurs critiques seulement
    avoid_empty_else: true
    avoid_print: false
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: false
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    
    # Désactiver les règles de style strictes
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false
    avoid_catches_without_on_clauses: false
    avoid_redundant_argument_values: false
    avoid_types_on_closure_parameters: false
    avoid_void_async: false
    curly_braces_in_flow_control_structures: false
    directives_ordering: false
    library_private_types_in_public_api: false
    omit_local_variable_types: false
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_in_for_each: false
    prefer_final_locals: false
    prefer_int_literals: false
    prefer_single_quotes: false
    sized_box_for_whitespace: false
    sort_child_properties_last: false
    sort_constructors_first: false
    unawaited_futures: false
    unnecessary_lambdas: false
    use_build_context_synchronously: false
    use_key_in_widget_constructors: false
    use_super_parameters: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  errors:
    # Transformer les erreurs en warnings
    invalid_annotation_target: ignore
    argument_type_not_assignable: warning
    invalid_assignment: warning
    non_bool_condition: warning
    non_bool_negation_expression: warning
    non_bool_operand: warning
    undefined_method: warning
    uri_does_not_exist: warning
    inference_failure_on_function_invocation: ignore
    inference_failure_on_function_return_type: ignore
    inference_failure_on_instance_creation: ignore
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
