targets:
  $default:
    builders:
      mockito|mockBuilder:
        generate_for:
          - test/**/*_test.dart
        options:
          # Generate mocks for all classes annotated with @GenerateMocks
          unsupported_members_strategy: "warn"
